import SOFTSTAKING_CONTRACT_ABI from "./abis/SoftStaking_ABI.json";
const SOFTSTAKING_ADDRESS = import.meta.env.VITE_SOFTSTAKING_ADDRESS;
const SOFTSTAKING_DATA_ENDPOINT = import.meta.env
	.VITE_SOFTSTAKING_DATA_ENDPOINT;

const WUSD_TOKEN_ADDRESS = import.meta.env.VITE_WUSD_TOKEN_ADDRESS;

const Constants = {
	SOFTSTAKING_ADDRESS,
	SOFTSTAKING_CONTRACT_ABI,
	SOFTSTAKING_DATA_ENDPOINT,
	WUSD_TOKEN_ADDRESS
};

export default Constants;
